#!/bin/sh

echo "Origin https remote url:"
echo ${DRONE_REMOTE_URL}

SSH_URL=$${SSH_ADDRESS_PREFIX}
REPONAME=${DRONE_REMOTE_URL#*$${HTTPS_ADDRESS_PREFIX}}
SSH_REPO=${SSH_URL}${REPONAME}
echo "Repo ssh address:"
echo ${SSH_REPO}


FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
        FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
        git init
        git remote add origin ${SSH_REPO}
fi

git config http.sslVerify "false"

# the branch may be empty for certain event types,
# such as github deployment events. If the branch
# is empty we checkout the sha directly. Note that
# we intentially omit depth flags to avoid failed
# clones due to lack of history.
if [[ -z "${DRONE_COMMIT_BRANCH}" ]]; then
	set -e
	set -x
	git fetch origin
	git checkout -qf ${DRONE_COMMIT_SHA}
	exit 0
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_COMMIT_BRANCH}:
git checkout ${DRONE_COMMIT_SHA} -b ${DRONE_COMMIT_BRANCH}